#include<stdio.h>
#include<stdlib.h>
#include<time.h>


int main()
{
	clock_t start_time,end_time;
	double execution_time;
	start_time = clock();
	/*It is done for noting the starting time of execution */
    int age;
    srand(time(0));
	/*time(0) is used to give different values in srand()  so in different time different random numbers are genarated*/
	int* agecount = (int*)calloc((101),sizeof(int));
	/*agecount array is used to find the frequency of the people of every age in the locality ranging from 0 to 100 */
    int* age_group_array = (int*)calloc((101)/10,sizeof(int));
	/*age_group_array is used to find the frequency of every age group like (0-10),(11-20) etc in the locality ranging from 0 to 100 */
    

    for ( int i = 0 ; i < 10000 ; i++ )
    {
        age = rand()%(101) ;
        /* Random numbers as ages are generated by rand() function */
        agecount[age]++;

        int group=(age-1)/10;
    /* If age is 92 then (age-1)/10 will give group no 9 so age-1 is divided by 10 to make actual groups */
        age_group_array[group]++;
    /* counting the frequencies of both age groups and individual ages */  
    }
    
     printf("\n\n***************The count of people of a particular age are*****************\n\n");
    for ( int i = 0 ; i <= 100 ; i++ )
    {
    	printf("Age %3d = %3d\t",i,agecount[i]);
	}
    printf("\n\nThe number of people in the age group (  0- 10) is ----  %d\n",age_group_array[0]);
    
    int max=age_group_array[0]/10;
    /* Here max is the variable created to find the largest frequency,it is divided by 10 as the bar plots are done with scale 1:10*/
    
    for ( int i = 1 ; i < 10 ; i++ )
    {
        printf("The number of people in the age group (%3d-%3d) is ----  %d\n", i*10 +1 , (i+1)*10 , age_group_array[i]);
        if(max<age_group_array[i]/10)
        max=age_group_array[i]/10;
        
    }

    printf("\n\nThe horizontal bar diagram with taking the scale 1:10\n\n");
    /* The horizontal bar diagram is printed using '*' in the scale 1 : 10 */
    /* horizontal bar diagram for (0-10) is done at first */
    printf("  0- 10 : ");
    for ( int i = 0 ; i < age_group_array[0]/10 ; i++ )   
    {
    	printf("*");
	}
    printf("\n");
    
    for ( int i = 1 ; i < 10 ; i++ )
    {   
        printf("%3d-%3d : ",i*10+1,(i+1)*10);
        for ( int j = 0 ; j < age_group_array[i]/10 ; j++ )
        {
            printf("*");
        }
        printf("\n");
        
    }
     printf("\n\nThe vertical bar diagram with taking the scale 1:10\n\n");

     /* At first we found the maximum among the age_group_array which is found initially. 
	    It is the number of times the outer for loop will run for vertical line diagram. 
		We will print *  using inner for loop. For the first row ,the age_group_array[j]/10 will match the maximum 
		then we will print * .
        So for this reason in every step we reduce the maximum by 1 and make a condition that if reduced maximum <= age_group_array[j] 
		then only we will print * otherwise will print '\t'.

    */
    for (int i = 0; i < max ; i++)
    {   
        
        for ( int j = 0 ; j < 10 ; j++ )
        {
          if(max>age_group_array[j]/10)
          printf("\t");

          else
          printf("*       ");
        }
        printf("\n");
        max--;
        
    }
    /* The age groups are also printed below the vertical bar diagram */
    printf("0- 10\t");
    for ( int i = 1 ; i < 10 ; i++ )
    {   
        printf("%d-%3d\t",i*10+1,(i+1)*10);
  	}
  	
  	/* The clock is ended */
  	end_time = clock();
  	execution_time = (double)(end_time - start_time)/CLOCKS_PER_SEC ;
  	/* The total time in seconds */
  	printf("\nThe total time of execution is %lf seconds\n",execution_time);
    return 0;
}
